### ISSUE TITLE
Uncaught Error: ENOENT

### ISSUE THREAD

**Issue by fl4p** [piotrdelikat/fet-datasheets#4]
Trying to run:
```
processDocuments('./datasheets/infineon');
```

gives me this error (seems related to example prompts?)

```
/usr/local/bin/node /Users/fab/dev/pv/fet-datasheets/dist/index.js
Debugger listening on ws://127.0.0.1:59200/5cfc2dde-0a4b-430e-adda-df0686f56cbd
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Images already exist for: infineon/AUIRFP4110
Reading images from: intermediate/infineon/AUIRFP4110/images
Found 0 images to preselect.
(node:45592) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Preselection complete. Returning parsed JSON: {"dataPages":["AP80N08D.1.png","AP80N08D.2.png"],"chartPages":{"V_plateau":"AP80N08D.3.png"},"dimensionsPages":["AP80N08D.5.png"]}
Reading images from: intermediate/infineon/AUIRFP4110/images
Found 2 images to analyze.
Processing image: intermediate/infineon/AUIRFP4110/images/AP80N08D.1.png
Waiting for the debugger to disconnect...
node:fs:561
  return binding.open(
                 ^

Error: ENOENT: no such file or directory, open 'intermediate/infineon/AUIRFP4110/images/AP80N08D.1.png'
    at Object.openSync (node:fs:561:18)
    at Object.readFileSync (node:fs:445:35)
    at /Users/fab/dev/pv/fet-datasheets/dist/utils/anthropic/extractData.js:30:46
    at Generator.next (<anonymous>)
    at /Users/fab/dev/pv/fet-datasheets/dist/utils/anthropic/extractData.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/fab/dev/pv/fet-datasheets/dist/utils/anthropic/extractData.js:4:12)
    at readValuesFromImagesAnthropic (/Users/fab/dev/pv/fet-datasheets/dist/utils/anthropic/extractData.js:22:12)
    at /Users/fab/dev/pv/fet-datasheets/dist/index.js:59:90
    at Generator.next (<anonymous>) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'intermediate/infineon/AUIRFP4110/images/AP80N08D.1.png'
}

Node.js v22.5.1

Process finished with exit code 1

```

**Comment by piotrdelikat** [comment]
Two examples was missing 0 before number name so sometimes preselection suggested files that do not exist.

**Comment by piotrdelikat** [comment]
Also some pdf's are password protected (SECURED), have no clue why, file opens in Acrobat, but fails to convert.
<img width="284" alt="Screenshot 2024-09-04 at 20 34 43" src="https://github.com/user-attachments/assets/d57786e8-a566-4763-8f93-a87a4734484b">

Error: Command failed: GPL Ghostscript 10.03.1: 
   **** This file requires a password for access.
   **** Error: Couldn't initialise file.
               Output may be incorrect.
   No pages will be processed (FirstPage > LastPage).

**Comment by piotrdelikat** [comment]
Script skips further processing if images were not created.

**Comment by fl4p** [comment]
Can you maybe specify an empty password to ghostscript?
I can read `FDP039N08B-F102.pdf` with tabula
